rate: 1
node_name: "vision"

basler:
  target_fps: 2
  max_allowed_delay_in_seconds: 1.0
  rotate_img: 270 # specify in degrees
  topic: "basler" # topic that we publish to: /node_name/topic
  camera_node: "/basler" # camera topic
  image_topic: "image_rect_color"
  publish_labelled_img: True
  has_depth: False
  run_continuous: False
  wait_for_services: True
  detect_arucos: False
  parent_frame: "vision_table_zero" # When publishing transforms, this is the base/parent frame from which they are published.
  work_surface_ignore_border_width: 100
  show_work_surface_detection: True

realsense:
  target_fps: 6
  max_allowed_delay_in_seconds: 1.0
  rotate_img: 0 # specify in degrees
  topic: "realsense" # topic that we publish to: /node_name/topic
  camera_node: "/realsense" # camera node
  image_topic: "color/camera_info"
  info_topic: "color/image_raw"
  depth_topic: "aligned_depth_to_color/image_raw"
  publish_labelled_img: True
  publish_depth_img: True
  publish_cluster_img: True
  has_depth: True
  run_continuous: False
  wait_for_services: True
  detect_arucos: False
  camera_height: 0.20 # height in meters
  parent_frame: 'panda_2/realsense' # When publishing TFs, this will be the parent frame.
  calibration_file: '/root/vision-pipeline/realsense_calib/realsense_calib.yaml'

# yolact config
obj_detection:
  yolact_dataset_file: data_limited/yolact/2022-05-02_kalo_qundis/dataset.json
  yolact_score_threshold: 0.55
